DROP TABLE IF EXISTS films CASCADE;
DROP TABLE IF EXISTS studios CASCADE;
DROP TABLE IF EXISTS actors CASCADE;
DROP TABLE IF EXISTS reviewers CASCADE;
DROP TABLE IF EXISTS reviews CASCADE;


CREATE TABLE studios (
  studio_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT,
  state TEXT,
  country TEXT
);

CREATE TABLE actors (
  actor_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  dob TEXT,
  pob TEXT
);

CREATE TABLE reviewers (
  reviewer_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  company TEXT NOT NULL
);

CREATE TABLE films (
  film_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  release TEXT NOT NULL,
  studio BIGINT NOT NULL REFERENCES studios(studio_id),
  actors JSONB[]
);

CREATE TABLE reviews (
  review_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  rating INT CHECK (rating<6 AND rating>0),
  reviewer BIGINT NOT NULL REFERENCES reviewers(reviewer_id),
  review VARCHAR(140) NOT NULL,
  film BIGINT NOT NULL REFERENCES films(film_id)
);